apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-xfn-aws
  annotations:
    meta.crossplane.io/maintainer: The Getting Started Organization <support@starter.org>
    meta.crossplane.io/source: github.com/jbw976/configuration-xfn-aws
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This starter configuration enables Crossplane composition functions (XFN) for AWS.
    meta.crossplane.io/readme: |
      This Configuration ensures that relevant packages are available in the
      control plane so the platform engineer can start building with composition
      functions (XFN) targeting AWS. Specifically, functions can be written with
      [function-go-templating](https://github.com/upbound/function-go-templating/)
      and IAM resources in the [Upbound Official AWS
      Provider](https://marketplace.upbound.io/providers/upbound/provider-aws).
spec:
  crossplane:
    version: ">=v1.14.0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-family-aws
      version: ">=v0.37.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-iam
      version: ">=v0.37.0"
    - function: xpkg.upbound.io/upbound/function-go-templating
      version: ">=v0.3.0"
    - function: xpkg.upbound.io/upbound/function-auto-ready
      version: ">=v0.2.1"
